<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Chapter&nbsp;14.&nbsp;Test-First Programming</title>
<link rel="stylesheet" href="Chapter%C2%A014.%C2%A0Test-First%20Programming_files/diveintopython.css" type="text/css">
<link rev="made" href="http://www.diveintopython.net/unit_testing/josh@servercobra.com">
<meta name="generator" content="DocBook XSL Stylesheets V1.52.2">
<meta name="keywords" content="Python, Dive Into Python, tutorial, object-oriented, programming, documentation, book, free">
<meta name="description" content="Python from novice to pro">
<link rel="home" href="http://www.diveintopython.net/" title="Dive Into Python">
<link rel="up" href="http://www.diveintopython.net/" title="Dive Into Python">
<link rel="previous" href="http://www.diveintopython.net/" title="13.6.&nbsp;Testing for sanity">
<link rel="next" href="http://www.diveintopython.net/" title="14.2.&nbsp;roman.py, stage 2">
<script src="Chapter%C2%A014.%C2%A0Test-First%20Programming_files/ca-pub-1879314568120827.js"></script><script src="Chapter%C2%A014.%C2%A0Test-First%20Programming_files/ga.js" async="" type="text/javascript"></script><script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-9740779-18']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script></head>
<body>
<style type="text/css">body{margin-top:0!important;padding-top:0!important;min-width:800px!important;}#wm-ipp a:hover{text-decoration:underline!important;}</style>
<table id="Header" summary="" cellpadding="0" cellspacing="0" border="0" width="100%">
<tbody><tr>
<td id="breadcrumb" colspan="5" align="left" valign="top">You are here: <a href="http://www.diveintopython.net/index.html">Home</a>&nbsp;&gt;&nbsp;<a href="http://www.diveintopython.net/toc/index.html">Dive Into Python</a>&nbsp;&gt;&nbsp;<span class="thispage">Test-First Programming</span></td>
<td id="navigation" align="right" valign="top">&nbsp;&nbsp;&nbsp;<a href="http://www.diveintopython.net/unit_testing/testing_for_sanity.html" title="Prev: “Testing for sanity”">&lt;&lt;</a>&nbsp;&nbsp;&nbsp;<a href="http://www.diveintopython.net/unit_testing/stage_2.html" title="Next: “roman.py, stage 2”">&gt;&gt;</a></td>
</tr>
<tr>

<td colspan="2" id="logocontainer">
<p style="float:left; margin:0 10px 1em 0"><a href="http://www.amazon.com/gp/product/1475198116/ref=as_li_tf_il?ie=UTF8&amp;tag=serve01-20&amp;linkCode=as2&amp;camp=1789&amp;creative=9325&amp;creativeASIN=1475198116"><img src="Chapter%C2%A014.%C2%A0Test-First%20Programming_files/q.asc" border="0"></a><img src="Chapter%C2%A014.%C2%A0Test-First%20Programming_files/ir.gif" alt="" style="border:none !important; margin:0px !important;" border="0" height="1" width="1"></p>


<h1 id="logo"><a href="http://www.diveintopython.net/index.html" accesskey="1">Dive Into Python</a></h1>
<p id="tagline">Python from novice to pro</p>
<img src="Chapter%C2%A014.%C2%A0Test-First%20Programming_files/amazon-buy-button.gif">
</td>
<td colspan="3" align="center">
<script type="text/javascript"><!--
google_ad_client = "ca-pub-1879314568120827";
/* DiveIntoPython */
google_ad_slot = "8002881514";
google_ad_width = 468;
google_ad_height = 60;
//-->
</script>
<script type="text/javascript" src="Chapter%C2%A014.%C2%A0Test-First%20Programming_files/show_ads.js">
</script><ins id="aswift_0_expand" style="display:inline-table;border:none;height:60px;margin:0;padding:0;position:relative;visibility:visible;width:468px;background-color:transparent"><ins id="aswift_0_anchor" style="display:block;border:none;height:60px;margin:0;padding:0;position:relative;visibility:visible;width:468px;background-color:transparent"><iframe marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" allowfullscreen="true" onload="var i=this.id,s=window.google_iframe_oncopy,H=s&amp;&amp;s.handlers,h=H&amp;&amp;H[i],w=this.contentWindow,d;try{d=w.document}catch(e){}if(h&amp;&amp;d&amp;&amp;(!d.body||!d.body.firstChild)){if(h.call){setTimeout(h,0)}else if(h.match){try{h=s.upd(h,i)}catch(e){}w.location.replace(h)}}" id="aswift_0" name="aswift_0" style="left:0;position:absolute;top:0;" frameborder="0" height="60" scrolling="no" width="468"></iframe></ins></ins>
</td>
<td colspan="3" align="right">
<form id="search" method="GET" action="http://www.google.com/custom">
<p><label for="q" accesskey="4">Find:&nbsp;</label><input id="q" name="q" size="20" maxlength="255" value=" " type="text"> <input value="Search" type="submit"><input name="cof" value="LW:752;L:http://diveintopython.org/images/diveintopython.png;LH:42;AH:left;GL:0;AWFID:3ced2bb1f7f1b212;" type="hidden"><input name="domains" value="diveintopython.org" type="hidden"><input name="sitesearch" value="diveintopython.org" type="hidden"></p>
</form>
<p><a href="https://github.com/pcsforeducation/diveintopython/issues?sort=created&amp;state=open">Report issues<img style="margin-left:10px" src="Chapter%C2%A014.%C2%A0Test-First%20Programming_files/logo_github.png" height="40"></a></p>
</td>
</tr>
</tbody></table>
<div class="chapter" lang="en">
<div class="titlepage">
<div>
<div>
<h2 class="title"><a name="roman1.5"></a>Chapter&nbsp;14.&nbsp;Test-First Programming
                  </h2>
</div>
</div>
<div></div>
</div>
<div class="toc">
<ul>
<li><span class="section"><a href="http://www.diveintopython.net/unit_testing/stage_1.html#roman.stage1">14.1. roman.py, stage 1</a></span></li>
<li><span class="section"><a href="http://www.diveintopython.net/unit_testing/stage_2.html">14.2. roman.py, stage 2</a></span></li>
<li><span class="section"><a href="http://www.diveintopython.net/unit_testing/stage_3.html">14.3. roman.py, stage 3</a></span></li>
<li><span class="section"><a href="http://www.diveintopython.net/unit_testing/stage_4.html">14.4. roman.py, stage 4</a></span></li>
<li><span class="section"><a href="http://www.diveintopython.net/unit_testing/stage_5.html">14.5. roman.py, stage 5</a></span></li>
</ul>
</div>
<div class="section" lang="en">
<div class="titlepage">
<div>
<div>
<h2 class="title"><a name="roman.stage1"></a>14.1.&nbsp;<tt class="filename">roman.py</tt>, stage 1
                     </h2>
</div>
</div>
<div></div>
</div>
<div class="abstract">
<p>Now that the unit tests are complete, it's time to start writing the 
code that the test cases are attempting to test.  You're
                  going to do this in stages, so you can see all the 
unit tests fail, then watch them pass one by one as you fill in the gaps
                  in <tt class="filename">roman.py</tt>.
               </p>
</div>
<div class="example"><a name="d0e32864"></a><h3 class="title">Example&nbsp;14.1.&nbsp;<tt class="filename">roman1.py</tt></h3>
<p>This file is available in <tt class="filename">py/roman/stage1/</tt> in the examples directory.
               </p>
<p>If you have not already done so, you can <a href="http://www.diveintopython.net/download/diveintopython-examples-5.4.zip" title="Download example scripts">download this and other examples</a> used in this book.
               </p><pre class="programlisting"><span class="pystring">"""Convert to and from Roman numerals"""</span>

<span class="pycomment">#Define exceptions</span>
<span class="pykeyword">class</span><span class="pyclass"> RomanError</span>(Exception): <span class="pykeyword">pass</span>                <a name="roman.stage1.1.1"></a><img src="Chapter%C2%A014.%C2%A0Test-First%20Programming_files/1.png" alt="1" border="0" height="12" width="12"><span class="pykeyword">
class</span> OutOfRangeError(RomanError): <span class="pykeyword">pass</span>          <a name="roman.stage1.1.2"></a><img src="Chapter%C2%A014.%C2%A0Test-First%20Programming_files/2.png" alt="2" border="0" height="12" width="12"><span class="pykeyword">
class</span> NotIntegerError(RomanError): <span class="pykeyword">pass</span>
<span class="pykeyword">class</span><span class="pyclass"> InvalidRomanNumeralError</span>(RomanError): <span class="pykeyword">pass</span> <a name="roman.stage1.1.3"></a><img src="Chapter%C2%A014.%C2%A0Test-First%20Programming_files/3.png" alt="3" border="0" height="12" width="12">

<span class="pykeyword">def</span><span class="pyclass"> toRoman</span>(n):
    <span class="pystring">"""convert integer to Roman numeral"""</span>
    <span class="pykeyword">pass</span>                                         <a name="roman.stage1.1.4"></a><img src="Chapter%C2%A014.%C2%A0Test-First%20Programming_files/4.png" alt="4" border="0" height="12" width="12">

<span class="pykeyword">def</span><span class="pyclass"> fromRoman</span>(s):
    <span class="pystring">"""convert Roman numeral to integer"""</span>
    <span class="pykeyword">pass</span>
</pre><div class="calloutlist">
<table summary="Callout list" border="0">
<tbody><tr>
<td align="left" valign="top" width="12"><a href="http://www.diveintopython.net/unit_testing/stage_1.html#roman.stage1.1.1"><img src="Chapter%C2%A014.%C2%A0Test-First%20Programming_files/1.png" alt="1" border="0" height="12" width="12"></a>
</td>
<td align="left" valign="top">This is how you define your own custom exceptions in <span class="application">Python</span>.  Exceptions are classes, and you create your own by subclassing existing exceptions.  It is strongly recommended (but not
                           required) that you subclass <tt class="errorcode">Exception</tt>, which is the base class that all built-in exceptions inherit from.  Here I am defining <tt class="errorcode">RomanError</tt> (inherited from <tt class="errorcode">Exception</tt>) to act as the base class for all my other custom exceptions to follow.  This is a matter of style; I could just as easily
                           have inherited each individual exception from the <tt class="errorcode">Exception</tt> class directly.
                        </td>
</tr>
<tr>
<td align="left" valign="top" width="12"><a href="http://www.diveintopython.net/unit_testing/stage_1.html#roman.stage1.1.2"><img src="Chapter%C2%A014.%C2%A0Test-First%20Programming_files/2.png" alt="2" border="0" height="12" width="12"></a>
</td>
<td align="left" valign="top">The <tt class="errorcode">OutOfRangeError</tt> and <tt class="errorcode">NotIntegerError</tt> exceptions will eventually be used by <tt class="function">toRoman</tt> to flag various forms of invalid input, as specified in <a href="http://www.diveintopython.net/unit_testing/testing_for_failure.html#roman.tobadinput.example" title="Example&nbsp;13.3.&nbsp;Testing bad input to toRoman"><tt class="classname">ToRomanBadInput</tt></a>.
                        </td>
</tr>
<tr>
<td align="left" valign="top" width="12"><a href="http://www.diveintopython.net/unit_testing/stage_1.html#roman.stage1.1.3"><img src="Chapter%C2%A014.%C2%A0Test-First%20Programming_files/3.png" alt="3" border="0" height="12" width="12"></a>
</td>
<td align="left" valign="top">The <tt class="errorcode">InvalidRomanNumeralError</tt> exception will eventually be used by <tt class="function">fromRoman</tt> to flag invalid input, as specified in <a href="http://www.diveintopython.net/unit_testing/testing_for_failure.html#roman.frombadinput.example" title="Example&nbsp;13.4.&nbsp;Testing bad input to fromRoman"><tt class="classname">FromRomanBadInput</tt></a>.
                        </td>
</tr>
<tr>
<td align="left" valign="top" width="12"><a href="http://www.diveintopython.net/unit_testing/stage_1.html#roman.stage1.1.4"><img src="Chapter%C2%A014.%C2%A0Test-First%20Programming_files/4.png" alt="4" border="0" height="12" width="12"></a>
</td>
<td align="left" valign="top">At this stage, you want to define the <span class="acronym">API</span> of each of your functions, but you don't want to code them yet, so you stub them out using the <span class="application">Python</span> reserved word <a href="http://www.diveintopython.net/object_oriented_framework/defining_classes.html#fileinfo.class.simplest" title="Example&nbsp;5.3.&nbsp;The Simplest Python Class"><tt class="literal">pass</tt></a>.
                        </td>
</tr>
</tbody></table>
</div>
</div>
<p>Now for the big moment (drum roll please): you're finally going to run the unit test against this stubby little module.  At
               this point, every test case should fail.  In fact, if any test case passes in stage 1, you should go back to <tt class="filename">romantest.py</tt> and re-evaluate why you coded a test so useless that it passes with do-nothing functions.
            </p>
<p>Run <tt class="filename">romantest1.py</tt> with the <tt class="option">-v</tt> command-line option, which will give more verbose output so you can see exactly what's going on as each test case runs. 
               With any luck, your output should look like this:
            </p>
<div class="example"><a name="roman.stage1.output"></a><h3 class="title">Example&nbsp;14.2.&nbsp;Output of <tt class="filename">romantest1.py</tt> against <tt class="filename">roman1.py</tt></h3><pre class="screen"><span class="computeroutput">fromRoman should only accept uppercase input ... ERROR
toRoman should always return uppercase ... ERROR
fromRoman should fail with malformed antecedents ... FAIL
fromRoman should fail with repeated pairs of numerals ... FAIL
fromRoman should fail with too many repeated numerals ... FAIL
fromRoman should give known result with known input ... FAIL
toRoman should give known result with known input ... FAIL
fromRoman(toRoman(n))==n for all n ... FAIL
toRoman should fail with non-integer input ... FAIL
toRoman should fail with negative input ... FAIL
toRoman should fail with large input ... FAIL
toRoman should fail with 0 input ... FAIL

======================================================================
ERROR: fromRoman should only accept uppercase input
----------------------------------------------------------------------
</span><span class="traceback">Traceback (most recent call last):
  File "C:\docbook\dip\py\roman\stage1\romantest1.py", line 154, in testFromRomanCase
    roman1.fromRoman(numeral.upper())
AttributeError: 'None' object has no attribute 'upper'</span><span class="computeroutput">
======================================================================
ERROR: toRoman should always return uppercase
----------------------------------------------------------------------
</span><span class="traceback">Traceback (most recent call last):
  File "C:\docbook\dip\py\roman\stage1\romantest1.py", line 148, in testToRomanCase
    self.assertEqual(numeral, numeral.upper())
AttributeError: 'None' object has no attribute 'upper'</span><span class="computeroutput">
======================================================================
FAIL: fromRoman should fail with malformed antecedents
----------------------------------------------------------------------
</span><span class="traceback">Traceback (most recent call last):
  File "C:\docbook\dip\py\roman\stage1\romantest1.py", line 133, in testMalformedAntecedent
    self.assertRaises(roman1.InvalidRomanNumeralError, roman1.fromRoman, s)
  File "c:\python21\lib\unittest.py", line 266, in failUnlessRaises
    raise self.failureException, excName
AssertionError: InvalidRomanNumeralError</span><span class="computeroutput">
======================================================================
FAIL: fromRoman should fail with repeated pairs of numerals
----------------------------------------------------------------------
</span><span class="traceback">Traceback (most recent call last):
  File "C:\docbook\dip\py\roman\stage1\romantest1.py", line 127, in testRepeatedPairs
    self.assertRaises(roman1.InvalidRomanNumeralError, roman1.fromRoman, s)
  File "c:\python21\lib\unittest.py", line 266, in failUnlessRaises
    raise self.failureException, excName
AssertionError: InvalidRomanNumeralError</span><span class="computeroutput">
======================================================================
FAIL: fromRoman should fail with too many repeated numerals
----------------------------------------------------------------------
</span><span class="traceback">Traceback (most recent call last):
  File "C:\docbook\dip\py\roman\stage1\romantest1.py", line 122, in testTooManyRepeatedNumerals
    self.assertRaises(roman1.InvalidRomanNumeralError, roman1.fromRoman, s)
  File "c:\python21\lib\unittest.py", line 266, in failUnlessRaises
    raise self.failureException, excName
AssertionError: InvalidRomanNumeralError</span><span class="computeroutput">
======================================================================
FAIL: fromRoman should give known result with known input
----------------------------------------------------------------------
</span><span class="traceback">Traceback (most recent call last):
  File "C:\docbook\dip\py\roman\stage1\romantest1.py", line 99, in testFromRomanKnownValues
    self.assertEqual(integer, result)
  File "c:\python21\lib\unittest.py", line 273, in failUnlessEqual
    raise self.failureException, (msg or '%s != %s' % (first, second))
AssertionError: 1 != None</span><span class="computeroutput">
======================================================================
FAIL: toRoman should give known result with known input
----------------------------------------------------------------------
</span><span class="traceback">Traceback (most recent call last):
  File "C:\docbook\dip\py\roman\stage1\romantest1.py", line 93, in testToRomanKnownValues
    self.assertEqual(numeral, result)
  File "c:\python21\lib\unittest.py", line 273, in failUnlessEqual
    raise self.failureException, (msg or '%s != %s' % (first, second))
AssertionError: I != None</span><span class="computeroutput">
======================================================================
FAIL: fromRoman(toRoman(n))==n for all n
----------------------------------------------------------------------
</span><span class="traceback">Traceback (most recent call last):
  File "C:\docbook\dip\py\roman\stage1\romantest1.py", line 141, in testSanity
    self.assertEqual(integer, result)
  File "c:\python21\lib\unittest.py", line 273, in failUnlessEqual
    raise self.failureException, (msg or '%s != %s' % (first, second))
AssertionError: 1 != None</span><span class="computeroutput">
======================================================================
FAIL: toRoman should fail with non-integer input
----------------------------------------------------------------------
</span><span class="traceback">Traceback (most recent call last):
  File "C:\docbook\dip\py\roman\stage1\romantest1.py", line 116, in testNonInteger
    self.assertRaises(roman1.NotIntegerError, roman1.toRoman, 0.5)
  File "c:\python21\lib\unittest.py", line 266, in failUnlessRaises
    raise self.failureException, excName
AssertionError: NotIntegerError</span><span class="computeroutput">
======================================================================
FAIL: toRoman should fail with negative input
----------------------------------------------------------------------
</span><span class="traceback">Traceback (most recent call last):
  File "C:\docbook\dip\py\roman\stage1\romantest1.py", line 112, in testNegative
    self.assertRaises(roman1.OutOfRangeError, roman1.toRoman, -1)
  File "c:\python21\lib\unittest.py", line 266, in failUnlessRaises
    raise self.failureException, excName
AssertionError: OutOfRangeError</span><span class="computeroutput">
======================================================================
FAIL: toRoman should fail with large input
----------------------------------------------------------------------
</span><span class="traceback">Traceback (most recent call last):
  File "C:\docbook\dip\py\roman\stage1\romantest1.py", line 104, in testTooLarge
    self.assertRaises(roman1.OutOfRangeError, roman1.toRoman, 4000)
  File "c:\python21\lib\unittest.py", line 266, in failUnlessRaises
    raise self.failureException, excName
AssertionError: OutOfRangeError</span><span class="computeroutput">
======================================================================
FAIL: toRoman should fail with 0 input                                 </span><a name="roman.stage1.2.1"></a><img src="Chapter%C2%A014.%C2%A0Test-First%20Programming_files/1.png" alt="1" border="0" height="12" width="12"><span class="computeroutput">
----------------------------------------------------------------------
</span><span class="traceback">Traceback (most recent call last):
  File "C:\docbook\dip\py\roman\stage1\romantest1.py", line 108, in testZero
    self.assertRaises(roman1.OutOfRangeError, roman1.toRoman, 0)
  File "c:\python21\lib\unittest.py", line 266, in failUnlessRaises
    raise self.failureException, excName
AssertionError: OutOfRangeError                                        </span><a name="roman.stage1.2.2"></a><img src="Chapter%C2%A014.%C2%A0Test-First%20Programming_files/2.png" alt="2" border="0" height="12" width="12"><span class="computeroutput">
----------------------------------------------------------------------
Ran 12 tests in 0.040s                                                 </span><a name="roman.stage1.2.3"></a><img src="Chapter%C2%A014.%C2%A0Test-First%20Programming_files/3.png" alt="3" border="0" height="12" width="12"><span class="computeroutput">

FAILED (failures=10, errors=2)                                         </span><a name="roman.stage1.2.4"></a><img src="Chapter%C2%A014.%C2%A0Test-First%20Programming_files/4.png" alt="4" border="0" height="12" width="12"></pre><div class="calloutlist">
<table summary="Callout list" border="0">
<tbody><tr>
<td align="left" valign="top" width="12"><a href="http://www.diveintopython.net/unit_testing/stage_1.html#roman.stage1.2.1"><img src="Chapter%C2%A014.%C2%A0Test-First%20Programming_files/1.png" alt="1" border="0" height="12" width="12"></a>
</td>
<td align="left" valign="top">Running the script runs <tt class="function">unittest.main()</tt>, which runs each test case, which is to say each method defined in each class within <tt class="filename">romantest.py</tt>.  For each test case, it prints out the <tt class="literal">doc string</tt> of the method and whether that test passed or failed.  As expected, none of the test cases passed.
                        </td>
</tr>
<tr>
<td align="left" valign="top" width="12"><a href="http://www.diveintopython.net/unit_testing/stage_1.html#roman.stage1.2.2"><img src="Chapter%C2%A014.%C2%A0Test-First%20Programming_files/2.png" alt="2" border="0" height="12" width="12"></a>
</td>
<td align="left" valign="top">For each failed test case, <tt class="filename">unittest</tt> displays the trace information showing exactly what happened.  In this case, the call to <tt class="function">assertRaises</tt> (also called <tt class="function">failUnlessRaises</tt>) raised an <tt class="errorcode">AssertionError</tt> because it was expecting <tt class="function">toRoman</tt> to raise an <tt class="errorcode">OutOfRangeError</tt> and it didn't.
                        </td>
</tr>
<tr>
<td align="left" valign="top" width="12"><a href="http://www.diveintopython.net/unit_testing/stage_1.html#roman.stage1.2.3"><img src="Chapter%C2%A014.%C2%A0Test-First%20Programming_files/3.png" alt="3" border="0" height="12" width="12"></a>
</td>
<td align="left" valign="top">After the detail, <tt class="filename">unittest</tt> displays a summary of how many tests were performed and how long it took.
                        </td>
</tr>
<tr>
<td align="left" valign="top" width="12"><a href="http://www.diveintopython.net/unit_testing/stage_1.html#roman.stage1.2.4"><img src="Chapter%C2%A014.%C2%A0Test-First%20Programming_files/4.png" alt="4" border="0" height="12" width="12"></a>
</td>
<td align="left" valign="top">Overall, the unit test failed because at least one test case did not pass.  When a test case doesn't pass, <tt class="filename">unittest</tt> distinguishes between failures and errors.  A failure is a call to an <tt class="function">assertXYZ</tt> method, like <tt class="function">assertEqual</tt> or <tt class="function">assertRaises</tt>, that fails because the asserted condition is not true or the expected exception was not raised.  An error is any other sort
                           of exception raised in the code you're testing or the unit test case itself.  For instance, the <tt class="function">testFromRomanCase</tt> method (“<span class="quote"><tt class="function">fromRoman</tt> should only accept uppercase input</span>”) was an error, because the call to <tt class="function">numeral.upper()</tt> raised an <tt class="errorcode">AttributeError</tt> exception, because <tt class="function">toRoman</tt> was supposed to return a string but didn't.  But <tt class="function">testZero</tt> (“<span class="quote"><tt class="function">toRoman</tt> should fail with 0 input</span>”) was a failure, because the call to <tt class="function">fromRoman</tt> did not raise the <tt class="errorcode">InvalidRomanNumeral</tt> exception that <tt class="function">assertRaises</tt> was looking for.
                        </td>
</tr>
</tbody></table>
</div>
</div>
</div>
</div>
<table class="Footer" summary="" cellpadding="0" cellspacing="0" border="0" width="100%">
<tbody><tr>
<td align="left" width="35%"><br><a class="NavigationArrow" href="http://www.diveintopython.net/unit_testing/testing_for_sanity.html">&lt;&lt;&nbsp;Testing for sanity</a></td>
<td align="center" width="30%"><br>&nbsp;<span class="divider">|</span>&nbsp;<span class="thispage">1</span> <span class="divider">|</span> <a href="http://www.diveintopython.net/unit_testing/stage_2.html" title="14.2.&nbsp;roman.py, stage 2">2</a> <span class="divider">|</span> <a href="http://www.diveintopython.net/unit_testing/stage_3.html" title="14.3.&nbsp;roman.py, stage 3">3</a> <span class="divider">|</span> <a href="http://www.diveintopython.net/unit_testing/stage_4.html" title="14.4.&nbsp;roman.py, stage 4">4</a> <span class="divider">|</span> <a href="http://www.diveintopython.net/unit_testing/stage_5.html" title="14.5.&nbsp;roman.py, stage 5">5</a>&nbsp;<span class="divider">|</span>&nbsp;
            </td>
<td align="right" width="35%"><br><a class="NavigationArrow" href="http://www.diveintopython.net/unit_testing/stage_2.html">roman.py, stage 2&nbsp;&gt;&gt;</a></td>
</tr>
<tr>
<td colspan="3"><br></td>
</tr>
</tbody></table>
<div class="Footer">
<script type="text/javascript"><!--
google_ad_client = "ca-pub-1879314568120827";
/* DiveIntoPython */
google_ad_slot = "8002881514";
google_ad_width = 468;
google_ad_height = 60;
//-->
</script>
<script type="text/javascript" src="Chapter%C2%A014.%C2%A0Test-First%20Programming_files/show_ads.js">
</script><ins id="aswift_1_expand" style="display:inline-table;border:none;height:60px;margin:0;padding:0;position:relative;visibility:visible;width:468px;background-color:transparent"><ins id="aswift_1_anchor" style="display:block;border:none;height:60px;margin:0;padding:0;position:relative;visibility:visible;width:468px;background-color:transparent"><iframe marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" allowfullscreen="true" onload="var i=this.id,s=window.google_iframe_oncopy,H=s&amp;&amp;s.handlers,h=H&amp;&amp;H[i],w=this.contentWindow,d;try{d=w.document}catch(e){}if(h&amp;&amp;d&amp;&amp;(!d.body||!d.body.firstChild)){if(h.call){setTimeout(h,0)}else if(h.match){try{h=s.upd(h,i)}catch(e){}w.location.replace(h)}}" id="aswift_1" name="aswift_1" style="left:0;position:absolute;top:0;" frameborder="0" height="60" scrolling="no" width="468"></iframe></ins></ins>
<p><a href="https://github.com/pcsforeducation/diveintopython/issues?sort=created&amp;state=open">Report issues<img style="margin-left:10px" src="Chapter%C2%A014.%C2%A0Test-First%20Programming_files/logo_github.png" height="40"></a></p>
<p class="copyright">Copyright © 2000, 2001, 2002, 2003, 2004 <a href="mailto:josh@servercobra.com">Mark Pilgrim</a></p>
</div>

</body></html>